server:
  port: 18080

spring:
  application:
      name: learn-security
  cloud:
    bootstrap:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:25432/learn
    username: learn
    password: sql
  data:
    rest:
      base-path: /api
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

custom-error-controller:
  debug: true
management:
  security:
    enabled: false
logging:
  level:
    org:
      springframework:
        security: DEBUG
