CREATE ROLE learn;
ALTER ROLE learn WITH SUPERUSER
INHERIT
CREATEROLE
CREATEDB
LOGIN
NOREPLICATION
NOBYPASSRLS
PASSWORD 'md5d7980ace5b59ea073a4c25bd767b9c8d';

CREATE DATABASE learn WITH TEMPLATE = template0 OWNER = postgres;
GRANT ALL ON DATABASE learn TO learn;
