version: '2'
services:
  jenkins:
    image: 'jenkins/jenkins:2.107.3'
    ports:
      - '2080:8080'
      - '50000:50000'
    volumes:
      - /Users/alekseysamoylov/Docker/data/jenkins:/var/jenkins_home
